apiVersion: apps/v1
kind: Deployment
metadata:
  name: scart
spec:
  selector:
    matchLabels:
      app: scart
  replicas : 1
  template:
    metadata:
      labels:
        app: scart
    spec:
      containers:
      - name: scart
        image: sudeeparyan/s-cart:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: scart
spec:
  type: NodePort
  selector:
    app: scart
  ports:
  - name: scart
    port: 3000
    targetPort: 3000
    nodePort: 30500


